name: CI/CD Development

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Prompt for commit message
        if: success()
        run: |
          echo "Tests passed. Please enter a commit message:"
          read commit_message
          if [ -z "$commit_message" ]; then
            echo "Commit message cannot be empty. Please try again."
            exit 1
          fi
          git config --global user.email "ricardocravo1992@gmail.com"
          git config --global user.name "Ricardocravo"
          git add .
          git commit -m "$commit_message"
          git push origin development

