name: Pull Request and Dead Code Cleanup
on:
  pull_request:
jobs:
  install:
    name: Installing packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn-lock') }}
      - name: Install dependencies
        run: yarn install
  dead-code-cleanup:
    name: Finding dead code
    runs-on: ubuntu-latest
    needs: install 
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn-lock') }}
      - name: Clean dead code
        run: yarn ts-prune --error
  testing:
    name: Unit tester
    runs-on: ubuntu-latest
    needs: install 
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn-lock') }}
      - name: Run unit tests 
        run: yarn test
  
