name: Pull Request Automation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Check for dead code
        run: yarn run ts-prune

      - name: Clean the code
        run: yarn clean

      - name: Test pull request changes
        run: yarn test